//import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import { sourceCodePro } from "./ui/fonts";
import "./ui/globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link rel="icon" href="images/favicon.ico" />
    </head>
    <body>
        <div className={`${sourceCodePro.className} nav`}>
            <Image
                src="/headerlogo.png"
                width={54}
                height={44}
                className="header-logo"
                alt="Site logo"
            />
            <div className="nav-links">
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>01.</b> About</p>
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>02.</b> Experience</p>
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>03.</b> Projects</p>
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>04.</b> Contact</p>
                <button className={`resume-button ${sourceCodePro.className}`}>Resume</button>
            </div>
        </div>
        {children}
        </body>
    </html>
  );
}
