//import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import { sourceCodePro } from "./ui/fonts";
import "./ui/globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import NavBar from "@/components/NavBar";

config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <title>cjcocokrisp.dev</title>
        <link rel="icon" href="images/favicon.ico" />
    </head>
        <body>
            {children}
        </body>
    </html>
  );
}

/*
<div className={`${sourceCodePro.className} nav`}>
            <Link href={'/'}>
                <Image
                    src="/headerlogo.png"
                    width={54}
                    height={44}
                    className="header-logo"
                    alt="Site logo"
                    
                />
            </Link>
            <div className="nav-links">
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>01.</b> <a href="/">About</a></p>
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>02.</b> <a href="/#experience">Experience</a></p>
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>03.</b> Projects</p>
                <p style={{color: "white"}}><b style={{color: "var(--text-red)"}}>04.</b> Contact</p>
                <button className={`resume-button ${sourceCodePro.className}`}>Resume</button>
            </div>
        </div>
*/
